variables:
  SONAR_TOKEN: $SONAR_PROJECT_LOGIN_FRONT

build-frontend-code-job:
  stage: build
  cache:
    - key:
        files:
          - frontend/package.json
      paths:
        - ${CI_PROJECT_DIR}/frontend/node_modules
  rules:
    - changes:
      - frontend/**/*
  script:
    - cd frontend
    - npm install
    - npm run build
  before_script:
    - echo "BUILD_CI_JOB_ID=$CI_JOB_ID" > frontend_build.env
  artifacts:
    paths:
      - frontend/dist/frontend
    reports:
      dotenv:
        - frontend_build.env

sonarqube-frontend-sast:
  stage: test
  needs: [build-frontend-code-job]
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd frontend
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=$SONAR_PROJECT_KEY_FRONT \

telegram-notification-frontend:
  stage: notify
  needs:
    - build-frontend-code-job
    - sonarqube-frontend-sast
  rules:
    - changes:
      - frontend/**/*
      if: $CI_COMMIT_TITLE =~ /send notification/
  script:
    - |
      curl --location "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage" \
      --header "Content-Type: application/json" \
      --data "{\"chat_id\": \"-1002007326342\",\"text\": \"Игорь Тютюнов собрал frontend. URL для скачивания артефактов
      $CI_PROJECT_URL/-/jobs/$BUILD_CI_JOB_ID/artifacts/download\"}"
