stages:
  - build
  - notify


build-backend-code-job:
  stage: build
  only:
    changes:
      - backend/*
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/*.jar

telegram-notification-backend:
  stage: notify
  needs:
    - build-backend-code-job
  only:
    changes:
      - backend/*
    variables:
      - $CI_COMMIT_TITLE =~ /send notification/
  script:
    - |
      curl --location "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage" \
      --header "Content-Type: application/json" \
      --data "{\"chat_id\": \"-1002007326342\",\"text\": \"Игорь Тютюнов собрал backend. URL для скачивания артефактов
      $CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/download?job=$CI_JOB_NAME\"}"