stages:
  - build
  - test
  - notify


build-backend-code-job:
  stage: build
  only:
    changes:
      - backend/*
  script:
    - cd backend
    - mvn package
  before_script:
    - echo "BUILD_CI_JOB_ID=$CI_JOB_ID" > backend_build.env
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
    reports:
      dotenv: backend_build.env

sonar-scanner-backend-job:
  stage: test
  script:
    - cd backend
    - mvn package
    - mvn sonar:sonar \
      -Dsonar.projectKey=75_IGORTYUTYUNOV_BACKEND \
      -Dsonar.host.url=https://sonarqube.praktikum-services.ru \
      -Dsonar.login=$BACKEND_SQ_TOKEN

telegram-notification-backend:
  stage: notify
  needs:
    - build-backend-code-job
  only:
    changes:
      - backend/*
    variables:
      - $CI_COMMIT_TITLE =~ /send notification/
  script:
    - |
      curl --location "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage" \
      --header "Content-Type: application/json" \
      --data "{\"chat_id\": \"-1002007326342\",\"text\": \"Игорь Тютюнов собрал backend. URL для скачивания артефактов
      $CI_PROJECT_URL/-/jobs/$BUILD_CI_JOB_ID/artifacts/download\"}"