variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - release
  - deploy
  - notify

build:
  stage: build
  cache:
    - key:
        files:
          - backend/pom.xml
      paths:
        - ${CI_PROJECT_DIR}/.m2/repository
  script:
    - cd backend
    - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
  before_script:
    - export BUILD_CI_JOB_ID=$CI_JOB_ID
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar

release:
  stage: release
  needs:
    - build
  script:
    - cd backend
    - >
      mvn deploy -DskipTests 
      -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository 
      -s settings.xml 
      -Dversion.application=${VERSION}
      

deploy:
  stage: deploy
  needs:
    - release
  script:
    - echo "Типа выполнили deploy бэка"

notify:
  stage: deploy
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TITLE =~ /send notification/
  script:
    - |
      curl --location "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage" \
      --header "Content-Type: application/json" \
      --data "{\"chat_id\": \"-1002007326342\",\"text\": \"Выполнен deploy backend-а. URL для скачивания 
      артефактов
      $CI_PROJECT_URL/-/jobs/$BUILD_CI_JOB_ID/artifacts/download\"}"
