
build-backend-code-job:
  stage: build
  cache:
    - key:
        files:
          - backend/pom.xml
      paths:
        - ${CI_PROJECT_DIR}/.m2/repository
  rules:
    - changes:
      - backend/**/*
  script:
    - cd backend
    - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
  before_script:
    - echo "BUILD_CI_JOB_ID=$CI_JOB_ID" > backend_build.env
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
    reports:
      dotenv: backend_build.env

telegram-notification-backend:
  stage: notify
  needs:
    - build-backend-code-job
  rules:
    - changes:
      - backend/**/*
      if: $CI_COMMIT_TITLE =~ /send notification/
  script:
    - |
      curl --location "https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage" \
      --header "Content-Type: application/json" \
      --data "{\"chat_id\": \"-1002007326342\",\"text\": \"Игорь Тютюнов собрал backend. URL для скачивания артефактов
      $CI_PROJECT_URL/-/jobs/$BUILD_CI_JOB_ID/artifacts/download\"}"

upload-backend-release:
  stage: release
  only:
    changes:
      - backend/**/*
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - >
      mvn deploy -DskipTests 
      -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository 
      -s settings.xml 
      -Dversion.application=${VERSION}